[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs-18_x', 'go']

[phases.frontend-install]
workDir = "frontend"
onlyIncludeFiles = [
    "package.json",
    "package-lock.json"
]
cmds = ["npm install"]

[phases.backend-install]
workDir = "backend"
onlyIncludeFiles = [
    "go.mod",
    "go.sum"
]
cmds = ["go mod download"]

[phases.frontend-build]
workDir = "frontend"
cmds = ["npm run build"]

[phases.backend-build]
workDir = "backend"
cmds = ["go build -o app ."]

[start]
cmd = "./backend/app"