[variables]
# Set any environment variables needed
NODE_ENV = "production"

# Configure the build phases
[phases.setup]
nixPkgs = ['nodejs-18_x', 'go']

[phases.install]
# Only include necessary files for dependency installation to optimize caching
onlyIncludeFiles = [
    "frontend/package.json",
    "frontend/package-lock.json", # or "pnpm-lock.yaml" if using pnpm
    "backend/go.mod",
    "backend/go.sum"
]
# Install frontend dependencies
cmds = [
    "npm --prefix ./frontend install", # or "pnpm install" if using pnpm
    "cd backend && go mod download && cd .."
]

[phases.build]
# Build the frontend first, then the Go backend
cmds = [
    "npm --prefix ./frontend run build",  # This should build Vite into the backend's dist directory
    "go build -o ./backend/app -C ./backend ."
]

[start]
# Start the Go server which will serve both the API and static files
cmd = "./backend/app"